create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  completed boolean not null default false,
  is_complete boolean generated always as (completed) stored,
  created_at timestamptz not null default now()
);

alter table public.habits
  add column if not exists is_complete boolean generated always as (completed) stored;

create table public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint not null references public.habits(id) on delete cascade,
  logged_on date not null default current_date,
  completed boolean not null default true,
  unique (habit_id, logged_on)
);

alter table public.habits enable row level security;
alter table public.daily_logs enable row level security;

create policy "Users can manage their habits" on public.habits
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage their daily logs" on public.daily_logs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into public.habits (user_id, name, completed)
select id, 'Drink a glass of water', false from auth.users limit 1;